services:
    kernel.listener.bigfoot_user_menu_listener:
        class: Bigfoot\Bundle\UserBundle\Listener\MenuListener
        tags:
            - { name: kernel.event_listener, event: bigfoot.menu.generate, method: onMenuGenerate }
    kernel.listener.bigfoot_user_kernel_listener:
        class: Bigfoot\Bundle\UserBundle\Listener\KernelListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
    form.type.user:
        class: Bigfoot\Bundle\UserBundle\Form\BigfootUserType
        arguments: [ @security.encoder_factory ]
        tags:
            - { name: form.type, alias: bigfoot_user }
    form.type.role_menu:
            class: Bigfoot\Bundle\UserBundle\Form\BigfootRoleMenuType
            arguments: [ @service_container ]
            tags:
                - { name: form.type, alias: bigfootrolemenutype }