<?php

namespace Bigfoot\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BigfootRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BigfootRoleRepository extends EntityRepository
{
}
